version: "1.0"
info:
  model: int-scaffold
packages:
- name: RAHSWithSpaceProject
  gitServerName: RAHS with Space
  gitUrl: https://github.com/rahuldemocenter/RAHSWithSpaceProject
  gitUsername: rahuldemocenter
  gitBranch: main
